spring.application.name=springBootTest
spring.profiles.active=dev
#????????
logging.level.root=info
logging.level.com.fengling.springboot=warn
#??????????
logging.file.name=log/xx.log
#?????????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  %level %logger{50}.%M %L:%m%n
#??
logging.pattern.file=logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  %level %logger{50}.%M %L:%m%n